### ISSUE TITLE
ServerGoalHandle properties called as methods?

### ISSUE THREAD

**Issue by gavanderhoorn** [DLu/simple_actions#1]
I haven't read the code in detail, but could it be these lines/methods:

https://github.com/DLu/simple_actions/blob/283a2b184295470a89f08238f0098702e3d341fe/simple_actions/simple_server.py#L59-L63

are trying to invoke what are actually properties ([here](https://github.com/ros2/rclpy/blob/c7feb4b70c33aaf22e8ad467605c0a58451299c9/rclpy/rclpy/action/server.py#L91-L100))?

**Comment by gavanderhoorn** [comment]
Friendly ping?

**Comment by DLu** [comment]
Yes, they are accessing those properties. Do you think they should be reimplemented as such here, or just invoked without parens?

**Comment by gavanderhoorn** [comment]
The latter.

[This](https://github.com/DLu/simple_actions/compare/main...gavanderhoorn:simple_actions:wip) is how I had to change things to stop Python from yelling at me.

**Comment by gavanderhoorn** [comment]
Friendly ping again.

**Comment by gavanderhoorn** [comment]
Thanks

**Comment by gavanderhoorn** [comment]
Will you also push a new release? Would make dependency management easier.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/36640
https://github.com/ros/rosdistro/pull/36699
https://github.com/ros/rosdistro/pull/36700
